{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lin.okhttpplugin",
    "module": "OkhttpPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "OkhttpPlugin-1.0.0.jar",
          "url": "OkhttpPlugin-1.0.0.jar",
          "size": 21605,
          "sha512": "327923edab8a6c96b9e6b5b4860fc13cb5658eeddc8857f27e41206b94738b5ceb02e973d5f1c705d205a0838f733972164ca56f240c0e477ef5daa50fa7e573",
          "sha256": "f2eff87a9faedc1f07908063eabf40c64526c59a53f57989ce6abf03ca3c5df0",
          "sha1": "d5afe597a882c836709c0e40f5d73afd6eb10590",
          "md5": "8b11ccbf7955e7bacd7abcb0d8fb673d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.11"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "6.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "6.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "6.0"
          }
        }
      ],
      "files": [
        {
          "name": "OkhttpPlugin-1.0.0.jar",
          "url": "OkhttpPlugin-1.0.0.jar",
          "size": 21605,
          "sha512": "327923edab8a6c96b9e6b5b4860fc13cb5658eeddc8857f27e41206b94738b5ceb02e973d5f1c705d205a0838f733972164ca56f240c0e477ef5daa50fa7e573",
          "sha256": "f2eff87a9faedc1f07908063eabf40c64526c59a53f57989ce6abf03ca3c5df0",
          "sha1": "d5afe597a882c836709c0e40f5d73afd6eb10590",
          "md5": "8b11ccbf7955e7bacd7abcb0d8fb673d"
        }
      ]
    }
  ]
}
