{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mao.asm",
    "module": "asm_test_plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "asm_test_plugin-1.0.1.jar",
          "url": "asm_test_plugin-1.0.1.jar",
          "size": 15979,
          "sha512": "395cc97783dcd31426eddae471d903488913a9e47d455eaea53b67f2d0de71423f57372492752e2a1084726a9043eb75f8bfbd4d5d1b3c5879a1a485d5991528",
          "sha256": "4d45ec28d15d288959f24e638fec9c5283c617e564fe5cefd5d3484be1501d7c",
          "sha1": "111249082837a91ebbd131f8249d7cb135db7ed9",
          "md5": "f9db1def66e0d7862f6e66a9d9ae6433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.0"
          }
        }
      ],
      "files": [
        {
          "name": "asm_test_plugin-1.0.1.jar",
          "url": "asm_test_plugin-1.0.1.jar",
          "size": 15979,
          "sha512": "395cc97783dcd31426eddae471d903488913a9e47d455eaea53b67f2d0de71423f57372492752e2a1084726a9043eb75f8bfbd4d5d1b3c5879a1a485d5991528",
          "sha256": "4d45ec28d15d288959f24e638fec9c5283c617e564fe5cefd5d3484be1501d7c",
          "sha1": "111249082837a91ebbd131f8249d7cb135db7ed9",
          "md5": "f9db1def66e0d7862f6e66a9d9ae6433"
        }
      ]
    }
  ]
}
